# Generated by Django 2.2.24 on 2021-12-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Lesson',
        ),
    ]
